# FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

EXPOSE 8000

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y build-essential git

COPY . .

RUN pip install -e .

CMD ["uvicorn", "llamp.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
