FROM python:3.11-slim

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y build-essential

COPY . .

RUN pip install -e .

ENV FLASK_APP=src/llamp/main.py

EXPOSE 8000

CMD ["uvicorn", "llamp.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
